import type { Capabilities, GenerationRequest, GenerationResponse, InferenceAdapter } from './adapter';
export const MOCK_LABEL = 'Example UI response — not generated by a released OpenVerifiableLLM model.';
export type MockScenario = 'success' | 'error' | 'empty' | 'timeout' | 'identity-mismatch';
export const capabilities: Capabilities = {
  mock: true, modes: ['base', 'conversation'], inputLimit: 2000, outputLimit: 128, strategy: 'greedy',
  releases: {
    base: { id: 'synthetic-base', repository: 'synthetic/not-a-release', revision: 'a'.repeat(40), root: 'b'.repeat(64) },
    conversation: { id: 'synthetic-chat', repository: 'synthetic/not-a-release', revision: 'c'.repeat(40), root: 'd'.repeat(64) },
  },
};
export function createMockAdapter(scenario: MockScenario = 'success', delay = 1200): InferenceAdapter {
  return {
    async capabilities() { return capabilities; },
    async generate(request: GenerationRequest, signal?: AbortSignal): Promise<GenerationResponse> {
      await new Promise<void>((resolve, reject) => {
        if (signal?.aborted) { reject(new DOMException('Request cancelled', 'AbortError')); return; }
        const timer = setTimeout(() => { signal?.removeEventListener('abort', abort); resolve(); }, delay);
        function abort() { clearTimeout(timer); signal?.removeEventListener('abort', abort); reject(new DOMException('Request cancelled', 'AbortError')); }
        signal?.addEventListener('abort', abort, { once: true });
      });
      if (scenario === 'error') throw new Error('Synthetic backend error. No model was called.');
      if (scenario === 'timeout') throw new Error('Synthetic request timeout. No model was called.');
      return {
        text: scenario === 'empty' ? '' : 'This scripted response exercises the interface only. It makes no claim about model provenance or response accuracy.',
        release: scenario === 'identity-mismatch' ? { ...request.release, root: 'f'.repeat(64) } : { ...request.release },
        settings: { ...request.settings }, mock: true,
      };
    },
  };
}
